### ISSUE TITLE
Feature: sys_history cleanup

### ISSUE THREAD

**Issue by jpmschuler** [lolli42/dbdoctor#93]
I just stumbled over `sys_history` including entries for deleted records.
I would understand to e.g. keep a `tt_content` item's history as long as the `pages` exists (so longer as the `tt_content` exists) although I know no means of accessing that.
But the `sys_history` entries exists for `tt_content` for deleted `pages` also (deleted as in no db row existing anymore, not deleted=1 column).

I oppose a cleanup of `sys_history` by age (as provided e.g. by a scheduler garbage collection task often used for `sys_log`) for some scenarios. But in general the age-based-cleanup should be a last resort, especially in the case of unaccessible data due to missing relations. Thus, I deem it important to have a cleanup based on existence of referenced record.

As I need to write that in the next few weeks nevertheless and "cleaning up non-referenced stuff" is one major feature of this extensions, **I wondered if I should add a PR here instead of creating another extension, so do you deem this a helpful addition to `EXT:dbdoctor`?**

If the answer is "yes": I'd assume a new feature should have no configuration options like all the other ones. So the rule implemented would just be:
- If sys_history.tablename and sys_history.recuid can't be resolved to an existing record, delete it.

**Comment by lolli42** [comment]
Well. My current opinion is "yes and no" ...

I think it's a bit too early for dbdoctor to implement details of sys_history. First, I'm unsure if we should really remove those entries from sys_history and "hard code" this into dbdoctor: Even if referenced rows do not exist anymore, there may still be value in those rows - for instance the information that an editor actually worked on something in the past. OTOH, I also get your point that sys_history rows pointing to not existing records are kinda useless.

However, maybe there's another solution: I recently talked with Achim Fritz (maintainer of ext:container) - That extension has a couple of "fixers" as well in order to update DB state when ext:container messed up something. It does that based on standalone code infrastructure that is not as sophisticated as the framework that dbdoctor provides, like inspecting the changes and similar. We thus had the idea to open up the HealthFactory for extensions: ext:container could then "hook" in there to register own checks/fixers (probably using 'before' and 'after' stuff from core's DependencyOrderingService). Since dbdoctor is still in early development, we'd probably mark that API as "on your own risk, may break" or similar, though. Still, it would enable 3rd party extensions to use dbdoctor ... *if* we follow this path, you could easily implement your sys_history things in an own extension, and still leverage the dbdoctor power, even if it will be "on your own risk" at least for now. What do you think?

**Comment by jpmschuler** [comment]
Wow, a registration for _HealthProviders_ would be a wonderful approach, for general extension and instance streamlining, thx a lot for considering this!
I get your decision for not adding sys_history related stuff; basically either CORE should decide and fix or there will be too many interpretations of requirements in the real world.

So 

- I'll close this here, 
- write the code in an extension,
- watch for a hook in future dbdoctor releases to add to that extension, and 
- would add a link here to that extension in the aftermath if anybody stumbles over this in the future for reference
